export const NBA_TEAMS = {
  ATL: 'Atlanta Hawks',
  BOS: 'Boston Celtics',
  BKN: 'Brooklyn Nets',
  CHA: 'Charlotte Hornets',
  CHI: 'Chicago Bulls',
  CLE: 'Cleveland Cavaliers',
  DAL: 'Dallas Mavericks',
  DEN: 'Denver Nuggets',
  DET: 'Detroit Pistons',
  GSW: 'Golden State Warriors',
  HOU: 'Houston Rockets',
  IND: 'Indiana Pacers',
  LAC: 'LA Clippers',
  LAL: 'Los Angeles Lakers',
  MEM: 'Memphis Grizzlies',
  MIA: 'Miami Heat',
  MIL: 'Milwaukee Bucks',
  MIN: 'Minnesota Timberwolves',
  NOP: 'New Orleans Pelicans',
  NYK: 'New York Knicks',
  OKC: 'Oklahoma City Thunder',
  ORL: 'Orlando Magic',
  PHI: 'Philadelphia 76ers',
  PHX: 'Phoenix Suns',
  POR: 'Portland Trail Blazers',
  SAC: 'Sacramento Kings',
  SAS: 'San Antonio Spurs',
  TOR: 'Toronto Raptors',
  UTA: 'Utah Jazz',
  WAS: 'Washington Wizards',
};

export const NBA_TEAM_LOGOS = {
  ATL: '@/assets/teamlogos/team-1.png',
  BOS: '@/assets/teamlogos/team-2.png',
  BKN: '@/assets/teamlogos/team-3.png',
  CHA: '@/assets/teamlogos/team-4.png',
  CHI: '@/assets/teamlogos/team-5.png',
  CLE: '@/assets/teamlogos/team-6.png',
  DAL: '@/assets/teamlogos/team-7.png',
  DEN: '@/assets/teamlogos/team-8.png',
  DET: '@/assets/teamlogos/team-9.png',
  GSW: '@/assets/teamlogos/team-10.png',
  HOU: '@/assets/teamlogos/team-11.png',
  IND: '@/assets/teamlogos/team-12.png',
  LAC: '@/assets/teamlogos/team-13.png',
  LAL: '@/assets/teamlogos/team-14.png',
  MEM: '@/assets/teamlogos/team-15.png',
  MIA: '@/assets/teamlogos/team-16.png',
  MIL: '@/assets/teamlogos/team-17.png',
  MIN: '@/assets/teamlogos/team-18.png',
  NOP: '@/assets/teamlogos/team-19.png',
  NYK: '@/assets/teamlogos/team-20.png',
  OKC: '@/assets/teamlogos/team-21.png',
  ORL: '@/assets/teamlogos/team-22.png',
  PHI: '@/assets/teamlogos/team-23.png',
  PHX: '@/assets/teamlogos/team-24.png',
  POR: '@/assets/teamlogos/team-25.png',
  SAC: '@/assets/teamlogos/team-26.png',
  SAS: '@/assets/teamlogos/team-27.png',
  TOR: '@/assets/teamlogos/team-28.png',
  UTA: '@/assets/teamlogos/team-29.png',
  WAS: '@/assets/teamlogos/team-30.png',
};